version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
